(source "jcs-elpa")
(source "melpa")
(source "gnu")

(package "buffer-menu-filter" "0.1.0" "Filter buffer-menu items using fake header")

(package-file "buffer-menu-filter.el")

(depends-on "emacs" "26.1")
(depends-on "buffer-menu-project")
(depends-on "flx")
(depends-on "ht")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
